"""add activities table

Revision ID: 0738e8b5b352
Revises: b73db6f974ae
Create Date: 2025-03-17 14:25:45.220476

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0738e8b5b352'
down_revision: Union[str, None] = 'b73db6f974ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_users_active_workspace_id_workspaces', 'users', type_='foreignkey')
    op.drop_column('users', 'active_workspace_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('active_workspace_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_foreign_key('fk_users_active_workspace_id_workspaces', 'users', 'workspaces', ['active_workspace_id'], ['id'])
    # ### end Alembic commands ###
