"""add role into association table

Revision ID: 245e9fb83cc2
Revises: dd6125931c36
Create Date: 2025-04-01 08:14:16.607539

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '245e9fb83cc2'
down_revision: Union[str, None] = 'dd6125931c36'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_workspace', sa.Column('role', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_workspace', 'role')
    # ### end Alembic commands ###
