"""fix primaryjoin issues

Revision ID: 434c305e2678
Revises: 9abba5a4cca1
Create Date: 2025-01-21 13:14:49.490955

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '434c305e2678'
down_revision: Union[str, None] = '9abba5a4cca1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('owner_id', sa.String(), nullable=False))
    op.create_foreign_key(None, 'events', 'users', ['owner_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'events', type_='foreignkey')
    op.drop_column('events', 'owner_id')
    # ### end Alembic commands ###
