"""add user_profile

Revision ID: 6d7e3ebeee75
Revises: 4d67003be51e
Create Date: 2025-03-19 03:56:26.429003

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6d7e3ebeee75'
down_revision: Union[str, None] = '4d67003be51e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Remove the drop table operations - we want to keep the activities table
    # op.drop_index('ix_activities_id', table_name='activities')
    # op.drop_table('activities')
    
    # Add user profile columns
    op.add_column('users', sa.Column('address', sa.String(), nullable=True))
    op.add_column('users', sa.Column('phone', sa.String(), nullable=True))
    op.add_column('users', sa.Column('timezone', sa.String(), nullable=True))
    op.add_column('users', sa.Column('bio', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('languages', sa.String(), nullable=True))
    op.add_column('users', sa.Column('last_login', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('cover_image_url', sa.String(), nullable=True))
    
    # Add marketing columns with default values to avoid NOT NULL constraint violations
    op.add_column('users', sa.Column('marketing_email', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('users', sa.Column('marketing_phone', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop the columns we added
    op.drop_column('users', 'marketing_phone')
    op.drop_column('users', 'marketing_email')
    op.drop_column('users', 'cover_image_url')
    op.drop_column('users', 'last_login')
    op.drop_column('users', 'languages')
    op.drop_column('users', 'bio')
    op.drop_column('users', 'timezone')
    op.drop_column('users', 'phone')
    op.drop_column('users', 'address')
    
    # We don't need to recreate the activities table since we're not dropping it in upgrade
    # ### end Alembic commands ###
