"""update file model

Revision ID: 6ec70fda561d
Revises: 6d7e3ebeee75
Create Date: 2025-03-19 07:13:50.669770

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6ec70fda561d'
down_revision: Union[str, None] = '6d7e3ebeee75'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_activities_id', table_name='activities')
    op.drop_table('activities')
    op.add_column('files', sa.Column('name', sa.String(), nullable=False))
    op.add_column('files', sa.Column('mime_type', sa.String(), nullable=True))
    op.add_column('files', sa.Column('size', sa.Integer(), nullable=True))
    op.add_column('files', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('files', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('files', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.add_column('files', sa.Column('workspace_id', sa.String(), nullable=False))
    op.add_column('files', sa.Column('folder_id', sa.String(), nullable=True))
    op.add_column('files', sa.Column('space', sa.Enum('INSURANCE', 'HOUSEHOLD', 'FINANCE', 'PETS', 'PERSONAL_DOCUMENTS', 'VEHICLES', 'TRAVEL', 'SPECIAL_EVENTS', name='itemspace'), nullable=True))
    op.add_column('files', sa.Column('version', sa.Integer(), nullable=False))
    op.alter_column('files', 'category',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_foreign_key(None, 'files', 'workspaces', ['workspace_id'], ['id'], ondelete='CASCADE')
    op.drop_column('files', 'folder')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('folder', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'files', type_='foreignkey')
    op.alter_column('files', 'category',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('files', 'version')
    op.drop_column('files', 'space')
    op.drop_column('files', 'folder_id')
    op.drop_column('files', 'workspace_id')
    op.drop_column('files', 'updated_at')
    op.drop_column('files', 'created_at')
    op.drop_column('files', 'description')
    op.drop_column('files', 'size')
    op.drop_column('files', 'mime_type')
    op.drop_column('files', 'name')
    op.create_table('activities',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('workspace_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('entity_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('entity_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('details', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='activities_user_id_fkey', onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name='activities_workspace_id_fkey', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='activities_pkey')
    )
    op.create_index('ix_activities_id', 'activities', ['id'], unique=False)
    # ### end Alembic commands ###
