"""update the db structure

Revision ID: 72dbc4bcd511
Revises: 01c9d446a8b4
Create Date: 2025-01-21 20:40:14.270717

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72dbc4bcd511'
down_revision: Union[str, None] = '01c9d446a8b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_workspace',
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('workspace_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], )
    )
    op.add_column('users', sa.Column('email_notification', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('users', sa.Column('sms_notification', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('users', sa.Column('push_notification', sa.Boolean(), nullable=False, server_default=sa.false()))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'push_notification')
    op.drop_column('users', 'sms_notification')
    op.drop_column('users', 'email_notification')
    op.drop_table('user_workspace')
    # ### end Alembic commands ###
