"""add_oauth_fields_to_users

Revision ID: 88182e4d9c60
Revises: c50d90479f14
Create Date: 2025-01-28 17:53:08.983046

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '88182e4d9c60'
down_revision: Union[str, None] = 'c50d90479f14'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('google_sub', sa.String(), nullable=True))
    op.add_column('users', sa.Column('apple_sub', sa.String(), nullable=True))
    op.add_column('users', sa.Column('oauth_provider', sa.String(), nullable=True))
    op.add_column('users', sa.Column('is_email_verified', sa.Boolean(), nullable=False, server_default=sa.text('FALSE')))
    op.create_unique_constraint(None, 'users', ['google_sub'])
    op.create_unique_constraint(None, 'users', ['apple_sub'])
    op.drop_column('users', 'refresh_token')
    op.drop_column('users', 'oauth_driver')
    op.drop_column('users', 'token_expires_at')
    op.drop_column('users', 'access_token')
    op.drop_column('users', 'oauth_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('oauth_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('access_token', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('token_expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('oauth_driver', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('refresh_token', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'is_email_verified')
    op.drop_column('users', 'oauth_provider')
    op.drop_column('users', 'apple_sub')
    op.drop_column('users', 'google_sub')
    # ### end Alembic commands ###
