"""feat task table

Revision ID: 9782cb636588
Revises: 5d0a5960872e
Create Date: 2025-03-19 15:21:45.169614

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9782cb636588'
down_revision: Union[str, None] = '5d0a5960872e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create enum types first
    taskpriority = sa.Enum('LOW', 'MEDIUM', 'HIGH', 'URGENT', name='taskpriority')
    taskpriority.create(op.get_bind())
    
    taskstatus = sa.Enum('ACTIVE', 'INACTIVE', 'ON_HOLD', 'COMPLETED', name='taskstatus')
    taskstatus.create(op.get_bind())
    
    tasktype = sa.Enum('GENERAL', 'MEETING', 'PROJECT', 'HOLIDAY', 'REMINDER', name='tasktype')
    tasktype.create(op.get_bind())
    
    # Add columns using the created enum types
    op.add_column('tasks', sa.Column('priority', taskpriority, nullable=False))
    op.add_column('tasks', sa.Column('status', taskstatus, nullable=False))
    op.add_column('tasks', sa.Column('type', tasktype, nullable=False))
    op.add_column('tasks', sa.Column('parent_id', sa.String(), nullable=True))
    op.add_column('tasks', sa.Column('position', sa.Integer(), nullable=False))
    op.add_column('tasks', sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.add_column('tasks', sa.Column('notifications', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.add_column('tasks', sa.Column('is_recurring', sa.Boolean(), nullable=False))
    op.add_column('tasks', sa.Column('recurrence_pattern', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.create_foreign_key(None, 'tasks', 'tasks', ['parent_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_column('tasks', 'recurrence_pattern')
    op.drop_column('tasks', 'is_recurring')
    op.drop_column('tasks', 'notifications')
    op.drop_column('tasks', 'tags')
    op.drop_column('tasks', 'position')
    op.drop_column('tasks', 'parent_id')
    op.drop_column('tasks', 'type')
    op.drop_column('tasks', 'status')
    op.drop_column('tasks', 'priority')
    
    # Drop enum types
    sa.Enum(name='tasktype').drop(op.get_bind())
    sa.Enum(name='taskstatus').drop(op.get_bind())
    sa.Enum(name='taskpriority').drop(op.get_bind())
    # ### end Alembic commands ###
