"""fix primaryjoin issues

Revision ID: 9abba5a4cca1
Revises: cfb055e02e47
Create Date: 2025-01-21 13:11:49.769486

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9abba5a4cca1'
down_revision: Union[str, None] = 'cfb055e02e47'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('workspace_id', sa.String(), nullable=False))
    op.create_foreign_key(None, 'events', 'workspaces', ['workspace_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'events', type_='foreignkey')
    op.drop_column('events', 'workspace_id')
    # ### end Alembic commands ###
