"""
add activity table

Revision ID: b73db6f974ae
Revises: 76bf68a31451
Create Date: 2025-03-13 16:05:32.117081

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b73db6f974ae'
down_revision: Union[str, None] = '76bf68a31451'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('lead', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'lead')
    # ### end Alembic commands ###
