"""update the db structure

Revision ID: c50d90479f14
Revises: 38d2c0588b52
Create Date: 2025-01-27 16:34:21.854026

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c50d90479f14'
down_revision: Union[str, None] = '38d2c0588b52'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_workspace',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('workspace_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'workspace_id')
    )
    op.drop_table('user_workspaces')
    op.alter_column('accommodations', 'arrival_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('accommodations', 'departure_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.create_index(op.f('ix_accommodations_id'), 'accommodations', ['id'], unique=False)
    op.add_column('items', sa.Column('description', sa.String(), nullable=True))
    op.alter_column('items', 'fields',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    op.add_column('tasks', sa.Column('workspace_id', sa.String(), nullable=False))
    op.add_column('tasks', sa.Column('description', sa.Text(), nullable=False))
    op.create_foreign_key(None, 'tasks', 'workspaces', ['workspace_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.add_column('users', sa.Column('access_token', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('refresh_token', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('token_expires_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('active_workspace_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'users', 'workspaces', ['active_workspace_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'active_workspace_id')
    op.drop_column('users', 'token_expires_at')
    op.drop_column('users', 'refresh_token')
    op.drop_column('users', 'access_token')
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_column('tasks', 'description')
    op.drop_column('tasks', 'workspace_id')
    op.alter_column('items', 'fields',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.drop_column('items', 'description')
    op.drop_index(op.f('ix_accommodations_id'), table_name='accommodations')
    op.alter_column('accommodations', 'departure_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('accommodations', 'arrival_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.create_table('user_workspaces',
    sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('workspace_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('profile_completion', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='user_workspaces_user_id_fkey'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name='user_workspaces_workspace_id_fkey'),
    sa.PrimaryKeyConstraint('user_id', 'workspace_id', name='user_workspaces_pkey')
    )
    op.drop_table('user_workspace')
    # ### end Alembic commands ###
