"""add user.created_at

Revision ID: c719594fa240
Revises: 31b0f35962ab
Create Date: 2025-01-21 14:14:42.124808

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c719594fa240'
down_revision: Union[str, None] = '31b0f35962ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('created_at', sa.String(), nullable=False, server_default="2025-01-01"))
    op.drop_index('ix_users_city', table_name='users')
    op.drop_index('ix_users_country', table_name='users')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_users_country', 'users', ['country'], unique=False)
    op.create_index('ix_users_city', 'users', ['city'], unique=False)
    op.drop_column('users', 'created_at')
    # ### end Alembic commands ###
