"""update the db structure

Revision ID: c8f501a34621
Revises: 72dbc4bcd511
Create Date: 2025-01-22 18:52:17.782881

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c8f501a34621'
down_revision: Union[str, None] = '72dbc4bcd511'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workspaces', sa.Column('stripe_id', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workspaces', 'stripe_id')
    # ### end Alembic commands ###
