"""fix primaryjoin issues

Revision ID: caba498df001
Revises: 434c305e2678
Create Date: 2025-01-21 13:19:06.489734

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'caba498df001'
down_revision: Union[str, None] = '434c305e2678'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('events_owner_id_fkey', 'events', type_='foreignkey')
    op.drop_column('events', 'owner_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('owner_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_foreign_key('events_owner_id_fkey', 'events', 'users', ['owner_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###
