"""feat workspace model

Revision ID: d76cd5ba6fc9
Revises: 4bfd560a52bc
Create Date: 2025-03-20 05:43:50.409438

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd76cd5ba6fc9'
down_revision: Union[str, None] = '4bfd560a52bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
