"""fixed workspace

Revision ID: f01d99a08b7b
Revises: 82340f29b047
Create Date: 2025-01-30 09:52:47.975867

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f01d99a08b7b'
down_revision: Union[str, None] = '82340f29b047'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workspaces', sa.Column('billing_plan', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workspaces', 'billing_plan')
    # ### end Alembic commands ###
