THREE_DAYS_TIMESTAMP = 259200

NINETY_DAYS_TIMESTAMP = 7776000

IPINFO_URL = "https://ipinfo.io/{}/json"

HEALTH_CHECK_ROUTE: str = "/probe/health"

SENTRY_ENVS = ["production"]

DISCOVER_FOLDER_LIMIT = 20

TAGS = [
    "Video Production",
    "2D Animation",
    "3D Animation",
    "Creature Design",
    "3D Modeling",
    "3D Printing",
    "3D Scanning",
    "3D Visualization",
    "AI Video",
    "Anatomy",
    "App Development",
    "Architectural Design",
    "Architectural Visualization",
    "VFX Supervision",
    "Art Direction",
    "Book Cover Illustration",
    "Cartooning",
    "Character Animation",
    "Character Design",
    "Character Modeling",
    "Cinematics",
    "Cloth Simulation",
    "Color Grading",
    "Color Management",
    "Compositing",
    "Concept Art",
    "Concept Design",
    "Costume Design",
    "Creature Modeling",
    "Digital Painting",
    "Digital Sculpting",
    "Drawing",
    "Environment Design",
    "Facial Rigging & Animation",
    "Fashion Design",
    "Film Editing",
    "Fluid Simulation",
    "Game Design",
    "Game Development",
    "Graphics Design",
    "HDRI Photography",
    "Hair/Fur Simulation",
    "Hard Surface Modeling",
    "High-poly Modeling",
    "Illustration",
    "Kitbashing",
    "Lighting",
    "Look Development",
    "Low-poly Modeling",
    "Map Design",
    "Marketing Illustration",
    "Matte Painting",
    "Medical Illustration",
    "Mel Scripting",
    "Motion Capture",
    "Motion Graphics",
    "Painting",
    "Particle Effects",
    "Photo-manipulation",
    "Photogrammetry",
    "Physically Based Rendering",
    "Portraiture",
    "Post-production",
    "Pre-viz",
    "Product Design",
    "Production Design",
    "Programming",
    "Project Management",
    "Prop Design",
    "Prop Modeling",
    "Python Scripting",
    "Rendering",
    "Retopology",
    "Rigging",
    "Rotoscoping",
    "Scientific Animation",
    "Screenwriting",
    "Sculpting",
    "Server Administration",
    "Shaders",
    "Shading",
    "Sketching",
    "Software Development",
    "Sound Design",
    "Storyboarding",
    "Storytelling",
    "Teaching",
    "Team Management",
    "Texturing",
    "Traditional Art",
    "Transport Design",
    "Typography",
    "UI Design",
    "UV Mapping",
    "User Interface Design",
    "Vector Illustration",
    "Vehicle Modeling",
    "Video Editing",
    "Visual Development",
    "Visual Effects",
    "Voice Acting",
    "Watercolors",
    "Weapon Design",
    "Weapon Modeling",
    "Web Design",
    "Web Development",
    "World Building",
    "3DBee",
    "Mol3D",
    "The Grove 3D",
    "3DF Zephyr",
    "Visual Designer 3D",
    "123D",
    "LightWave 3D",
    "Unfold 3D",
    "3D-Coat",
    "3ds Max",
    "After Effects",
    "Arnold",
    "Blender",
    "Cinema 4D",
    "Clip Studio Paint",
    "DAZ Studio",
    "GIMP",
    "Illustrator",
    "Keyshot",
    "Krita",
    "Manga Studio",
    "Mari",
    "Marmoset",
    "Marvelous Designer",
    "Maya",
    "Mental Ray",
    "Mol",
    "Mudbox",
    "Nuke",
    "Painter",
    "PaintTool Sal",
    "Photoshop",
    "Procreate",
    "Quixel Suite",
    "Sketchbook Pro",
    "Substance Designer",
    "Substance Painter",
    "Unity",
    "Unreal Engine",
    "V-Ray",
    "xNormal",
    "Zbrush",
    "Houdini",
    "Redshift",
    "Xgen",
    "Yeti",
    "Python",
    "Makehuman",
    "Arnold",
    "Alias Design",
    "Blackmagic Design Fusion",
    "Marvelous Designer",
    "InDesign",
    "Affinity Designer",
    "Maverick",
    "Amadine",
    "MasterpieceVR",
    "Braid Maker",
    "RenderMan",
    "Artomatix",
    "EmberGen",
    "Amberlight",
    "Combustion",
    "Shotgun",
    "PTGui",
    "Quill",
    "Tayasui Sketches",
    "Tayasui Sketches Mobile App",
    "Tayasui Sketches Pro",
    "MotionBuilder",
    "CoreIDRAW Graphics Suite",
    "SketchUp",
    "PyxelEdit",
    "Hard Ops",
    "HardMesh",
    "Realtime Board",
    "Storyboard Pro",
    "World",
    "Dreams",
    "Avid Media Composer",
    "GIMP",
    "CrazyBump",
    "Poser",
    "Final Draft",
    "PlantCatalog",
    "RealityCapture",
    "finalRender",
    "Balsamiq Mockup",
    "Adobe XD",
    "Adobe Lightroom",
    "Pencil2D",
    "Live2D",
    "Spine 2D",
    "DAZ Studio",
    "Fstorm",
    "Substance Source",
    "Sublime Text",
    "Maxwell Render",
    "Octane Render",
    "Hydra Render",
    "Corona Render",
    "GuerillaRender",
    "LuxRender",
    "Thea Render",
    "Twinmotion",
    "Modo",
    "Mocha",
    "Harmony",
    "Mixamo",
    "Marmoset Toolbag",
    "Presagis Creator",
]
